--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/GrosserZak/DropProtection
build-by-default: true
branches:
- main
projects:
  DropProtection:
    path: ""
    icon: "DropProtection.gif"
...
